version: '3.9'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: imagelite
    ports:
      - '5435:5432'
    volumes:
      - /data:/var/lib/postgresql/data
    networks:
      - imagelitenetwork

  sbootapp:
    build:
      dockerfile: Dockerfile
      context: ./backend
    container_name: imageliteapi
    restart: on-failure
    depends_on:
      - db
    ports:
      - '8080:8080'
    networks:
      - imagelitenetwork
    environment:
      POSTGRES_HOST: db

  app:
    build:
      dockerfile: Dockerfile
      context: ./frontend/imagelite
    container_name: imageliteapp
    restart: on-failure
    depends_on:
      - sbootapp
    ports:
      - '3000:3000'
    networks:
      - imagelitenetwork
    expose:
      - 3000


networks:
  imagelitenetwork:
    driver: bridge